# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'youtube_downloader_Qt.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(433, 582)
        MainWindow.setMinimumSize(QtCore.QSize(433, 582))
        MainWindow.setMaximumSize(QtCore.QSize(433, 582))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, -10, 441, 601))
        self.frame.setStyleSheet("QFrame{\n"
"background-color: rgb(197, 197, 197);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 40, 391, 51))
        self.label.setStyleSheet("QLabel{\n"
"color: rgb(157, 0, 0);\n"
"    font: 81 16pt \"Rockwell Extra Bold\";\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 231, 16))
        self.label_2.setStyleSheet("QLabel{\n"
"    color: rgb(6, 135, 255);\n"
"font: 75 12pt \"MV Boli\";\n"
"\n"
"}")
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        self.lineEdit.setGeometry(QtCore.QRect(40, 190, 341, 22))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
"\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(40, 240, 191, 21))
        self.label_3.setStyleSheet("QLabel{\n"
"    color: rgb(6, 135, 255);\n"
"font: 75 12pt \"MV Boli\";\n"
"\n"
"}")
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 290, 341, 22))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(130, 350, 151, 41))
        self.label_4.setStyleSheet("QLabel{\n"
"    font: 8pt \"Rockwell\";\n"
"font-size:20px;\n"
"color: rgb(0, 0, 0);\n"
"    \n"
"}")
        self.label_4.setObjectName("label_4")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setGeometry(QtCore.QRect(110, 400, 101, 41))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setGeometry(QtCore.QRect(220, 400, 101, 31))
        self.radioButton_2.setObjectName("radioButton_2")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(140, 490, 111, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"background-color: rgb(188, 188, 188);\n"
"    color: rgb(0, 0, 0);\n"
"    font: 75 12pt \"MS Shell Dlg 2\";\n"
"\n"
"}")
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Youtube Downloader"))
        self.label_2.setText(_translate("MainWindow", "Video URl Link:"))
        self.label_3.setText(_translate("MainWindow", "Exit Path:"))
        self.label_4.setText(_translate("MainWindow", "Select Format"))
        self.radioButton.setText(_translate("MainWindow", "Mp4"))
        self.radioButton_2.setText(_translate("MainWindow", "Mp3"))
        self.pushButton.setText(_translate("MainWindow", "DOWNLOAD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
